### ISSUE TITLE
Crash upon loading a world

### ISSUE THREAD

**Issue by yamikaitou** [Lunatrius/Schematica#98] opened 2015-10-22 02:22 UTC
Crash upon loading an existing or new world.
fml-client-latest.txt: https://gist.github.com/yamikaitou/c9584ccda5f759ca061c

Using Java 1.8_60, ATLauncher 3.2.3.1 with [Xisuminati Mod Pack](https://www.atlauncher.com/pack/Xisuminati), Minecraft 1.7.10, Forge 10.13.4.1492

**Comment by Lunatrius** [comment] 2015-10-22 03:18
Duplicate of #96. It's up to the Gilded Games Utils author to backport the fix.

You won't be able to use Schematica until that fix is backported to 1.7.10.

**Closed by Lunatrius** 2015-10-22 03:18 UTC
