### ISSUE TITLE
Enhancement - Allow player to substitute schematica blocks for others.

### ISSUE THREAD

**Issue by Arcrammer** [Lunatrius/Schematica#71] opened 2015-01-25 09:05 UTC
I think it would be a wonderful idea to allow the player the abiity to substitute one block for another (especially double slabs considering their buggy nature) before printing the schematica.

**Comment by Lunatrius** [comment] 2015-01-25 13:46
Duplicate of #49.

**Closed by Lunatrius** 2015-01-25 13:46 UTC
Labels: duplicate
