### ISSUE TITLE
Crashing Issue when pasting Schematic

### ISSUE THREAD

**Issue by Kozs** [Lunatrius/Schematica#146] opened 2016-05-30 02:45 UTC
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 5/29/16 10:43 PM
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.getId(Ljava/lang/Object;)I
	at com.github.lunatrius.schematica.world.storage.Schematic.setBlockState(Schematic.java:63)
	at com.github.lunatrius.schematica.world.schematic.SchematicAlpha.readFromNBT(SchematicAlpha.java:87)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:37)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:46)
	at com.github.lunatrius.schematica.proxy.ClientProxy.loadSchematic(ClientProxy.java:234)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.loadSchematic(GuiSchematicLoad.java:173)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146284_a(GuiSchematicLoad.java:87)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146274_d(GuiSchematicLoad.java:63)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.lunatrius.schematica.world.storage.Schematic.setBlockState(Schematic.java:63)
	at com.github.lunatrius.schematica.world.schematic.SchematicAlpha.readFromNBT(SchematicAlpha.java:87)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:37)
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.readFromFile(SchematicFormat.java:46)
	at com.github.lunatrius.schematica.proxy.ClientProxy.loadSchematic(ClientProxy.java:234)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.loadSchematic(GuiSchematicLoad.java:173)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146284_a(GuiSchematicLoad.java:87)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
	at com.github.lunatrius.core.client.gui.GuiScreenBase.func_73864_a(GuiScreenBase.java:44)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
	at com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad.func_146274_d(GuiSchematicLoad.java:63)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)

-- Affected screen --
Details:
	Screen name: com.github.lunatrius.schematica.client.gui.load.GuiSchematicLoad

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Loses'/238, l='MpServer', x=-17.49, y=69.00, z=278.90]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-12,64,283), Chunk: (at 4,4,11 in -1,17; contains blocks -16,0,272 to -1,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 102 game time, 102 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 124 total; [EntityCreeper['Creeper'/1538, l='MpServer', x=16.48, y=60.00, z=285.00], EntityCreeper['Creeper'/1795, l='MpServer', x=-36.50, y=18.00, z=280.50], EntityZombie['Zombie'/1800, l='MpServer', x=-34.50, y=31.00, z=243.50], EntityCreeper['Creeper'/1552, l='MpServer', x=-72.50, y=33.00, z=355.50], EntityBat['Bat'/789, l='MpServer', x=-39.56, y=31.70, z=295.17], EntityZombie['Zombie'/1563, l='MpServer', x=-46.50, y=43.00, z=250.50], EntityZombie['Zombie'/541, l='MpServer', x=-86.50, y=49.00, z=281.50], EntityZombie['Zombie'/1569, l='MpServer', x=-16.50, y=25.00, z=351.50], EntityFallingBlock['Falling Block'/1832, l='MpServer', x=10.50, y=16.00, z=176.50], EntityFallingBlock['Falling Block'/1833, l='MpServer', x=9.50, y=16.00, z=175.50], EntityFallingBlock['Falling Block'/1834, l='MpServer', x=20.50, y=26.00, z=195.50], EntityFallingBlock['Falling Block'/1835, l='MpServer', x=16.50, y=26.00, z=198.50], EntityFallingBlock['Falling Block'/1836, l='MpServer', x=17.50, y=25.67, z=198.50], EntityFallingBlock['Falling Block'/1837, l='MpServer', x=16.50, y=26.00, z=200.50], EntityFallingBlock['Falling Block'/1838, l='MpServer', x=16.50, y=26.00, z=199.50], EntityBat['Bat'/303, l='MpServer', x=-19.50, y=14.52, z=317.96], EntityFallingBlock['Falling Block'/1839, l='MpServer', x=15.50, y=26.00, z=198.50], EntityFallingBlock['Falling Block'/1840, l='MpServer', x=16.50, y=26.00, z=201.50], EntityFallingBlock['Falling Block'/1841, l='MpServer', x=17.50, y=25.67, z=199.50], EntityFallingBlock['Falling Block'/1842, l='MpServer', x=17.50, y=25.67, z=200.50], EntityFallingBlock['Falling Block'/1843, l='MpServer', x=18.50, y=25.67, z=199.50], EntityCreeper['Creeper'/820, l='MpServer', x=-28.50, y=33.00, z=258.50], EntityFallingBlock['Falling Block'/1844, l='MpServer', x=15.50, y=28.67, z=189.50], EntityBat['Bat'/565, l='MpServer', x=-24.79, y=28.76, z=238.64], EntityFallingBlock['Falling Block'/1845, l='MpServer', x=15.50, y=27.67, z=190.50], EntityFallingBlock['Falling Block'/1846, l='MpServer', x=15.50, y=28.67, z=188.50], EntityFallingBlock['Falling Block'/1847, l='MpServer', x=14.50, y=28.67, z=184.50], EntityFallingBlock['Falling Block'/1848, l='MpServer', x=21.50, y=4.00, z=208.50], EntityFallingBlock['Falling Block'/1608, l='MpServer', x=-15.50, y=19.00, z=306.50], EntityFallingBlock['Falling Block'/1609, l='MpServer', x=-15.50, y=19.00, z=307.50], EntitySkeleton['Skeleton'/1866, l='MpServer', x=42.50, y=23.00, z=295.50], EntityFallingBlock['Falling Block'/1613, l='MpServer', x=-16.50, y=19.00, z=305.50], EntityFallingBlock['Falling Block'/1614, l='MpServer', x=-15.50, y=19.00, z=305.50], EntityFallingBlock['Falling Block'/1615, l='MpServer', x=-15.50, y=20.00, z=304.50], EntityFallingBlock['Falling Block'/1617, l='MpServer', x=-16.50, y=20.00, z=304.50], EntityFallingBlock['Falling Block'/1620, l='MpServer', x=-16.50, y=20.00, z=303.50], EntitySheep['Sheep'/85, l='MpServer', x=-56.50, y=71.00, z=218.50], EntitySheep['Sheep'/86, l='MpServer', x=-57.50, y=69.00, z=216.50], EntityFallingBlock['Falling Block'/1622, l='MpServer', x=-16.50, y=20.00, z=302.50], EntitySheep['Sheep'/87, l='MpServer', x=-57.50, y=69.00, z=219.50], EntityFallingBlock['Falling Block'/1623, l='MpServer', x=-17.50, y=20.00, z=302.50], EntitySheep['Sheep'/88, l='MpServer', x=-58.50, y=65.00, z=221.50], EntityFallingBlock['Falling Block'/1624, l='MpServer', x=-17.50, y=20.00, z=303.50], EntitySheep['Sheep'/89, l='MpServer', x=-71.50, y=79.00, z=294.14], EntitySheep['Sheep'/90, l='MpServer', x=-69.50, y=78.00, z=293.50], EntitySheep['Sheep'/91, l='MpServer', x=-70.50, y=78.00, z=292.50], EntityFallingBlock['Falling Block'/1627, l='MpServer', x=-17.50, y=20.00, z=301.50], EntitySheep['Sheep'/92, l='MpServer', x=-71.50, y=80.25, z=295.03], EntityChicken['Chicken'/93, l='MpServer', x=-66.50, y=71.00, z=283.50], EntityBat['Bat'/349, l='MpServer', x=-47.20, y=39.00, z=263.58], EntityChicken['Chicken'/94, l='MpServer', x=-64.50, y=69.00, z=282.50], EntityChicken['Chicken'/95, l='MpServer', x=-65.50, y=72.00, z=285.50], EntityChicken['Chicken'/96, l='MpServer', x=-65.07, y=75.00, z=287.70], EntitySkeleton['Skeleton'/1120, l='MpServer', x=-34.50, y=16.00, z=249.50], EntityBat['Bat'/1132, l='MpServer', x=-25.40, y=33.40, z=254.82], EntitySheep['Sheep'/109, l='MpServer', x=-54.28, y=72.00, z=356.49], EntitySheep['Sheep'/110, l='MpServer', x=-50.50, y=73.00, z=354.50], EntitySheep['Sheep'/111, l='MpServer', x=-51.50, y=73.00, z=354.50], EntitySheep['Sheep'/112, l='MpServer', x=-52.50, y=73.00, z=347.50], EntitySheep['Sheep'/113, l='MpServer', x=-19.50, y=71.00, z=209.50], EntitySheep['Sheep'/114, l='MpServer', x=-19.50, y=71.00, z=211.50], EntitySheep['Sheep'/115, l='MpServer', x=-19.50, y=71.00, z=210.50], EntitySheep['Sheep'/116, l='MpServer', x=-19.50, y=71.00, z=209.50], EntityZombie['Zombie'/1656, l='MpServer', x=-21.50, y=32.00, z=252.50], EntityCreeper['Creeper'/378, l='MpServer', x=4.50, y=46.00, z=253.50], EntityZombie['Zombie'/1415, l='MpServer', x=-21.50, y=36.00, z=251.50], EntitySpider['Spider'/1416, l='MpServer', x=-66.50, y=20.00, z=291.50], EntitySheep['Sheep'/137, l='MpServer', x=18.42, y=78.00, z=220.52], EntitySheep['Sheep'/138, l='MpServer', x=17.48, y=78.00, z=220.52], EntitySheep['Sheep'/139, l='MpServer', x=13.50, y=77.00, z=219.50], EntitySheep['Sheep'/140, l='MpServer', x=17.46, y=69.00, z=275.26], EntitySheep['Sheep'/141, l='MpServer', x=15.50, y=69.00, z=278.50], EntitySheep['Sheep'/142, l='MpServer', x=18.50, y=69.00, z=278.50], EntitySheep['Sheep'/143, l='MpServer', x=16.50, y=69.00, z=278.50], EntitySkeleton['Skeleton'/1938, l='MpServer', x=-5.50, y=34.00, z=309.50], EntityBat['Bat'/405, l='MpServer', x=40.25, y=36.05, z=312.31], EntitySheep['Sheep'/152, l='MpServer', x=35.50, y=75.00, z=252.50], EntitySheep['Sheep'/153, l='MpServer', x=29.50, y=74.00, z=250.50], EntitySheep['Sheep'/154, l='MpServer', x=26.50, y=73.00, z=249.50], EntitySheep['Sheep'/155, l='MpServer', x=37.50, y=75.00, z=249.50], EntityZombie['Zombie'/923, l='MpServer', x=-70.50, y=38.00, z=336.50], EntityBat['Bat'/1179, l='MpServer', x=5.65, y=36.57, z=293.50], EntityCreeper['Creeper'/1693, l='MpServer', x=35.50, y=25.00, z=299.50], EntitySkeleton['Skeleton'/1191, l='MpServer', x=-43.50, y=31.00, z=251.50], EntityBat['Bat'/1194, l='MpServer', x=8.80, y=23.05, z=346.01], EntitySquid['Squid'/431, l='MpServer', x=42.19, y=55.67, z=320.60], EntityZombie['Zombie'/433, l='MpServer', x=-57.50, y=62.00, z=266.50], EntityBat['Bat'/1201, l='MpServer', x=-15.75, y=24.00, z=353.04], EntityFallingBlock['Falling Block'/1713, l='MpServer', x=7.50, y=19.36, z=282.50], EntityFallingBlock['Falling Block'/1714, l='MpServer', x=8.50, y=19.36, z=282.50], EntityFallingBlock['Falling Block'/1715, l='MpServer', x=6.50, y=20.36, z=282.50], EntityFallingBlock['Falling Block'/1716, l='MpServer', x=7.50, y=20.36, z=281.50], EntityZombie['Zombie'/702, l='MpServer', x=37.50, y=25.00, z=296.50], EntityBat['Bat'/708, l='MpServer', x=6.28, y=23.00, z=339.07], EntitySkeleton['Skeleton'/1478, l='MpServer', x=-49.50, y=31.00, z=277.50], EntityBat['Bat'/715, l='MpServer', x=-15.60, y=30.00, z=274.41], EntityFallingBlock['Falling Block'/1741, l='MpServer', x=3.50, y=35.00, z=297.50], EntityFallingBlock['Falling Block'/1742, l='MpServer', x=2.50, y=35.00, z=298.50], EntityFallingBlock['Falling Block'/1743, l='MpServer', x=2.50, y=36.00, z=299.50], EntityFallingBlock['Falling Block'/1744, l='MpServer', x=2.50, y=35.00, z=297.50], EntityFallingBlock['Falling Block'/1745, l='MpServer', x=3.50, y=35.00, z=296.50], EntityFallingBlock['Falling Block'/1746, l='MpServer', x=4.50, y=36.00, z=296.50], EntityFallingBlock['Falling Block'/1747, l='MpServer', x=5.50, y=36.00, z=296.50], EntityFallingBlock['Falling Block'/1748, l='MpServer', x=2.50, y=35.00, z=296.50], EntityFallingBlock['Falling Block'/1749, l='MpServer', x=0.50, y=35.00, z=297.50], EntityFallingBlock['Falling Block'/1750, l='MpServer', x=1.50, y=35.00, z=296.50], EntityFallingBlock['Falling Block'/1751, l='MpServer', x=1.50, y=35.00, z=297.50], EntityZombie['Zombie'/728, l='MpServer', x=24.50, y=17.00, z=275.50], EntityFallingBlock['Falling Block'/1752, l='MpServer', x=1.50, y=35.00, z=298.50], EntitySkeleton['Skeleton'/1498, l='MpServer', x=-47.50, y=27.00, z=210.50], EntitySkeleton['Skeleton'/731, l='MpServer', x=-50.50, y=16.00, z=283.50], EntityWitch['Witch'/1508, l='MpServer', x=-67.50, y=23.00, z=305.50], EntityBat['Bat'/743, l='MpServer', x=-13.93, y=17.00, z=325.21], EntityZombie['Zombie'/1256, l='MpServer', x=-23.50, y=26.00, z=277.50], EntitySkeleton['Skeleton'/490, l='MpServer', x=-25.50, y=27.00, z=250.50], EntityPlayerSP['Loses'/238, l='MpServer', x=-17.49, y=69.00, z=278.90], EntityZombie['Zombie'/1775, l='MpServer', x=13.50, y=35.00, z=298.50], EntitySkeleton['Skeleton'/1264, l='MpServer', x=-62.50, y=21.00, z=301.50], EntityFallingBlock['Falling Block'/1778, l='MpServer', x=4.50, y=89.06, z=380.50], EntityFallingBlock['Falling Block'/1780, l='MpServer', x=4.50, y=89.06, z=381.50], EntityFallingBlock['Falling Block'/1781, l='MpServer', x=5.50, y=89.06, z=380.50], EntityFallingBlock['Falling Block'/1782, l='MpServer', x=5.50, y=89.06, z=381.50], EntityFallingBlock['Falling Block'/1783, l='MpServer', x=3.50, y=89.06, z=380.50], EntityFallingBlock['Falling Block'/1784, l='MpServer', x=4.50, y=90.06, z=379.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 239915744 bytes (228 MB) / 712560640 bytes (679 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.23 Powered by Forge 12.16.1.1934 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1934.jar) 
	UCHIJAAAA	Forge{12.16.1.1934} [Minecraft Forge] (forge-1.9-12.16.1.1934.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.33} [LunatriusCore] (LunatriusCore-1.9-1.1.2.33-universal.jar) 
	UCHIJAAAA	Schematica{1.7.7.144} [Schematica] (Schematica-1.9-1.7.7.144-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.72' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Launched Version: 1.9-forge1.9-12.16.1.1934
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.72, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
```

Forge Version: (1.9) - 1934

**Comment by RedNesto** [comment] 2016-05-30 12:01
I think It's a duplicate of #145.

First of all, update [Schematica](https://mods.io/mods/1008/versions/1170/download), [LunatriusCore](https://mods.io/mods/1025/versions/1156/download) and eventually Forge to the [latest recommended release](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.9.html).

**Comment by Lunatrius** [comment] 2016-05-30 14:29
Correct, #119

**Closed by Lunatrius** 2016-05-30 14:29 UTC
Labels: duplicate
