### ISSUE TITLE
Save Schematic Crash

### ISSUE THREAD

**Issue by Psykat777** [Lunatrius/Schematica#100] opened 2015-10-28 10:10 UTC
Crashes every time I try to save build, no matter the size. Have tried with as few as 4 blocks even.
New to crash report posting, hope this is correct.

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2015/10/28 11:58 AM
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access method net.minecraft.nbt.NBTTagCompound.func_150298_a(Ljava/lang/String;Lnet/minecraft/nbt/NBTBase;Ljava/io/DataOutput;)V from class com.github.lunatrius.schematica.world.schematic.SchematicFormat
	at com.github.lunatrius.schematica.world.schematic.SchematicFormat.writeToFile(SchematicFormat.java:59)
	at com.github.lunatrius.schematica.handler.QueueTickHandler.processQueue(QueueTickHandler.java:71)
	at com.github.lunatrius.schematica.handler.QueueTickHandler.onServerTick(QueueTickHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_QueueTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:288)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:642)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 129617840 bytes (123 MB) / 418963456 bytes (399 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1450 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1450.jar) 
	UCHIJAAAA	Forge{11.14.3.1450} [Minecraft Forge] (forge-1.8-11.14.3.1450.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.28} [LunatriusCore] (LunatriusCore-1.8-1.1.2.28-universal.zip) 
	UCHIJAAAA	Schematica{1.7.7.130} [Schematica] (Schematica-1.8-1.7.7.130-universal.zip) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Psykat_SA'/610, l='test', x=-56.30, y=68.00, z=-74.56]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Lunatrius** [comment] 2015-10-28 12:17
Duplicate of #65. Your files end in `.zip` instead of `.jar`. Rename them manually or re-download the files.

**Closed by Lunatrius** 2015-10-28 12:17 UTC

**Comment by Psykat777** [comment] 2015-10-28 12:19
Thank you so much. Apologies that it wasted your time, I really appreciate it. I was so baffled.
