### ISSUE TITLE
Image destorted

### ISSUE THREAD

**Issue by Nytetears** [Lunatrius/Schematica#268] opened 2017-09-26 19:47 UTC
I am not sure how to explain this but when I try to use Schematica I get a distorted image. It builds find but the image is messed up. see the picture
![distorted image](https://user-images.githubusercontent.com/32307042/30880932-0aecad20-a2d2-11e7-98fa-26939de33060.jpg)

**Comment by Pokechu22** [comment] 2017-09-26 19:52
Duplicate of #258.

This is caused by optifine, but can usually be fixed by toggling VBOs in video settings.

**Comment by Nytetears** [comment] 2017-09-27 02:19
Thank you!!!

**Closed** 2017-09-27 09:13 UTC
Labels: duplicate, mc-1.12, optifine
