### ISSUE TITLE
Minecraft crashes whenever I try to print something in Schematica

### ISSUE THREAD

**Issue by 19englishm** [Lunatrius/Schematica#181] opened 2016-11-07 13:58 UTC
Hey so I just downloaded schematica and Luminous Core for 1.7.10 because the server I play on uses 1.7.10. As a test in a single player world, I copied a tree and got the schematica laid out, but then when I tried to print it, minecraft crashed.  This is the crash message that comes up.

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 11/7/16 8:54 AM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.block.Block.getPickBlock(Lnet/minecraft/util/MovingObjectPosition;Lnet/minecraft/world/World;IIILnet/minecraft/entity/player/EntityPlayer;)Lnet/minecraft/item/ItemStack;
	at com.github.lunatrius.schematica.client.util.BlockToItemStack.getItemStack(BlockToItemStack.java:14)
	at com.github.lunatrius.schematica.client.printer.SchematicPrinter.placeBlock(SchematicPrinter.java:169)
	at com.github.lunatrius.schematica.client.printer.SchematicPrinter.print(SchematicPrinter.java:114)
	at com.github.lunatrius.schematica.handler.client.TickHandler.onClientTick(TickHandler.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_49_TickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2053)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.lunatrius.schematica.client.util.BlockToItemStack.getItemStack(BlockToItemStack.java:14)
	at com.github.lunatrius.schematica.client.printer.SchematicPrinter.placeBlock(SchematicPrinter.java:169)
	at com.github.lunatrius.schematica.client.printer.SchematicPrinter.print(SchematicPrinter.java:114)
	at com.github.lunatrius.schematica.handler.client.TickHandler.onClientTick(TickHandler.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_49_TickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['MagicalMonkey44'/38, l='MpServer', x=-742.70, y=5.62, z=809.41]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-708,4,794), Chunk: (at 12,0,10 in -45,49; contains blocks -720,0,784 to -705,255,799), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 4296 game time, 4296 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 36 total; [EntityPixelmon['entity.pixelmon.Pixelmon.name'/64, l='MpServer', x=-750.26, y=4.84, z=878.20], EntityPixelmon['entity.pixelmon.Pixelmon.name'/66, l='MpServer', x=-745.93, y=4.55, z=887.68], EntityPixelmon['entity.pixelmon.Pixelmon.name'/67, l='MpServer', x=-708.50, y=4.00, z=733.50], EntityTrainer['entity.pixelmon.Trainer.name'/68, l='MpServer', x=-832.63, y=4.00, z=764.00], EntityPixelmon['entity.pixelmon.Pixelmon.name'/69, l='MpServer', x=-804.94, y=4.00, z=791.06], EntityPixelmon['entity.pixelmon.Pixelmon.name'/75, l='MpServer', x=-842.25, y=4.00, z=837.66], EntityPixelmon['entity.pixelmon.Pixelmon.name'/76, l='MpServer', x=-743.50, y=4.00, z=756.50], EntityPixelmon['entity.pixelmon.Pixelmon.name'/77, l='MpServer', x=-740.84, y=4.00, z=720.25], EntityPixelmon['entity.pixelmon.Pixelmon.name'/81, l='MpServer', x=-698.95, y=4.00, z=819.29], EntityPixelmon['entity.pixelmon.Pixelmon.name'/82, l='MpServer', x=-662.30, y=4.00, z=828.40], EntityPixelmon['entity.pixelmon.Pixelmon.name'/27, l='MpServer', x=-752.96, y=4.00, z=718.69], EntityPixelmon['entity.pixelmon.Pixelmon.name'/28, l='MpServer', x=-755.15, y=4.00, z=719.31], EntityPixelmon['entity.pixelmon.Pixelmon.name'/29, l='MpServer', x=-744.72, y=4.00, z=750.48], EntityPixelmon['entity.pixelmon.Pixelmon.name'/30, l='MpServer', x=-743.97, y=4.00, z=748.81], EntityPixelmon['entity.pixelmon.Pixelmon.name'/32, l='MpServer', x=-740.47, y=4.00, z=850.47], EntityPixelmon['entity.pixelmon.Pixelmon.name'/33, l='MpServer', x=-722.25, y=7.73, z=893.02], EntityTrainer['entity.pixelmon.Trainer.name'/36, l='MpServer', x=-691.50, y=4.00, z=881.50], EntityTrainer['entity.pixelmon.Trainer.name'/37, l='MpServer', x=-670.50, y=4.00, z=880.50], EntityClientPlayerMP['MagicalMonkey44'/38, l='MpServer', x=-742.70, y=5.62, z=809.41], EntityPixelmon['entity.pixelmon.Pixelmon.name'/40, l='MpServer', x=-784.66, y=4.00, z=835.22], EntityPixelmon['entity.pixelmon.Pixelmon.name'/41, l='MpServer', x=-784.94, y=4.00, z=831.47], EntityPixelmon['entity.pixelmon.Pixelmon.name'/47, l='MpServer', x=-817.52, y=4.00, z=894.48], EntityPixelmon['entity.pixelmon.Pixelmon.name'/49, l='MpServer', x=-726.17, y=4.00, z=854.32], EntityPixelmon['entity.pixelmon.Pixelmon.name'/50, l='MpServer', x=-735.71, y=4.00, z=848.11], EntityPixelmon['entity.pixelmon.Pixelmon.name'/51, l='MpServer', x=-722.78, y=4.00, z=845.50], EntityPixelmon['entity.pixelmon.Pixelmon.name'/52, l='MpServer', x=-734.74, y=4.00, z=848.31], EntityPixelmon['entity.pixelmon.Pixelmon.name'/53, l='MpServer', x=-721.50, y=4.00, z=855.81], EntityPixelmon['entity.pixelmon.Pixelmon.name'/55, l='MpServer', x=-777.50, y=4.00, z=731.50], EntityPixelmon['entity.pixelmon.Pixelmon.name'/56, l='MpServer', x=-779.06, y=4.00, z=726.34], EntityPixelmon['entity.pixelmon.Pixelmon.name'/57, l='MpServer', x=-770.64, y=4.00, z=728.17], EntityPixelmon['entity.pixelmon.Pixelmon.name'/121, l='MpServer', x=-700.11, y=8.17, z=842.41], EntityPixelmon['entity.pixelmon.Pixelmon.name'/59, l='MpServer', x=-686.50, y=4.00, z=856.47], EntityPixelmon['entity.pixelmon.Pixelmon.name'/123, l='MpServer', x=-808.28, y=4.00, z=736.72], EntityPixelmon['entity.pixelmon.Pixelmon.name'/124, l='MpServer', x=-805.72, y=4.00, z=738.25], EntityPixelmon['entity.pixelmon.Pixelmon.name'/125, l='MpServer', x=-807.50, y=4.00, z=734.53], EntityPixelmon['entity.pixelmon.Pixelmon.name'/63, l='MpServer', x=-689.50, y=4.00, z=884.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 381623792 bytes (363 MB) / 981110784 bytes (935 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 6 mods loaded, 6 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	pixelmon{3.5.0} [Pixelmon] (Pixelmon-1.7.10-3.5.1-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Schematica{1.7.6.131} [Schematica] (Schematica-1.7.10-1.7.6.131-universal (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1230
	LWJGL: 2.9.1
	OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-10.14.73, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

**Comment by Lunatrius** [comment] 2016-11-07 15:02
Duplicate of #95. Update Forge to **10.13.2.1234** or later and you should be fine.

**Closed by Lunatrius** 2016-11-07 15:02 UTC
Labels: duplicate
