### ISSUE TITLE
Schematica BUG

### ISSUE THREAD

**Issue by raphaNEWRICH** [Lunatrius/Schematica#379] opened 2018-08-26 14:00 UTC
I can not reconstruct my things, the images are all pulled and bugged. 
![2018-08-26_00 19 55](https://user-images.githubusercontent.com/33809044/44628909-2420a680-a91f-11e8-8f61-98e95ae87782.png)
![2018-08-26_10 51 31](https://user-images.githubusercontent.com/33809044/44628910-24b93d00-a91f-11e8-9014-b8059f09b415.png)
![2018-08-26_10 54 04](https://user-images.githubusercontent.com/33809044/44628911-24b93d00-a91f-11e8-971c-15ae519c850d.png)

**Comment by Lunatrius** [comment] 2018-08-26 14:58
Duplicate of #258. It's an incompatibility with Optifine. You can try turning off VBOs in the options or remove Optifine.

**Closed as completed by Lunatrius** 2018-08-26 14:58 UTC
Labels: duplicate, optifine, incompatibility
