### ISSUE TITLE
Bugged blocks?

### ISSUE THREAD

**Issue by SeQQuPL** [Lunatrius/Schematica#332] opened 2018-05-15 18:27 UTC
![2018-05-15_20 25 51](https://user-images.githubusercontent.com/39313344/40076087-426a362a-587e-11e8-9009-77358a8e2df7.png) I need fast answer

**Comment by Pokechu22** [comment] 2018-05-15 18:28
Duplicate of #258; caused by optifine.  You can remove optifine, or try disabling VBOs.

**Comment by SeQQuPL** [comment] 2018-05-15 18:44
Thanks !

**Closed as completed** 2018-05-16 00:28 UTC
Labels: duplicate, optifine, incompatibility
