### ISSUE TITLE
Possible plugin interference (with anti pvp cheating / grieffing)

### ISSUE THREAD

**Issue by marbit** [Lunatrius/Schematica#290] opened 2017-11-20 15:15 UTC
______________________________________________________________
NOTE: I found out that his entry issue has been reported by another person.
Feature request stands (see solution part).
You can see the other entry at https://github.com/Lunatrius/Schematica/issues/234
______________________________________________________________

**Problem** 
Printing with schematica seems not to work in the server (massivecraft)

**Description** 
Blocks placement is not registering, that is, blocks are placed and immediately eliminated. fml-client-lattest.log does not mention printing being disabled.

**Diagnosis** 
I suspect plugins to prevent cheating in pvp  or prevent griefing are at fault. It seems the server only registers blocks placed where the player crosshairs meet. I tested this by trying to print a line of wool with print distance adjusted to 1. When I watched the position where the block needed to be placed, the server registered it, otherwise the block was removed after it was set.

**Solution**
I request to add an option to only place blocks where the pointer is.

**Comment by Lunatrius** [comment] 2017-11-23 17:57
As you noticed yourself this is a duplicate of #234, so I'm closing this issue.

**Closed by Lunatrius** 2017-11-23 17:57 UTC
Labels: duplicate, incompatibility, printer
