### ISSUE TITLE
Schematica-1.8-1.7.7.130-universal white screen

### ISSUE THREAD

**Issue by SethGodzhell** [Lunatrius/Schematica#84] opened 2015-06-22 21:07 UTC
So here's a fairly strange issue, every time I try to load the latest version to Schematics, it loads perfectly fine... but the title screen appears white and I can't click on anything within the window.
(NOTE: everything works and starts up fine if I don't include Schematica. Even if I try to not include lunatriuscore, it whitescreens without the "You need mod X to run mod Y" screen)

Log of latest load attempt- http://pastebin.com/niLqQtNa

Mods that I attempted to load-
CodeChickenCore-1.8-1.0.5.36-universal 
CodeChickenLib-1.8-1.1.2.133-universal
LunatriusCore-1.7.10-1.1.2.21-universal
MapWriter-1.8-2.2.5
MouseTweaks-2.5.0-mc1.8
NotEnoughItems-1.8-1.0.5.104-universal 
Schematica-1.8-1.7.7.130-universal
WorldHandler-1.8-2.7
Liteloader 1.8 beta

Forge versions attempted-
forge-1.8-11.14.3.1474
forge-1.8-11.14.2.1430
forge-1.8-11.14.3.1450

**Comment by Lunatrius** [comment] 2015-06-22 22:42
Until I get this patched, Forge 1390 should work fine (possibly some of the later versions as well).

**Comment by SethGodzhell** [comment] 2015-06-26 01:24
alright, after some testing, it seems that it loads fine on Forge 1474 if I don't have liteloader loaded.

**Comment by Lunatrius** [comment] 2015-06-26 14:21
Weird. I've tried loading up an instance on Forge 1450 with Liteloader, LunatriusCore, Schematica and MouseTweaks (only mod that seems to have an optional LL dependency) and I haven't gotten the white screen.

Mind hopping into [this](http://webchat.esper.net/?nick=&channels=%23lunatrius) IRC channel when you have some time (I'm usually on around 1PM ~ 1AM GMT+0)? I know other people experienced this issue with other mods, but I want to make sure my fix actually fixes the issue.

**Comment by Lunatrius** [comment] 2015-06-26 18:00
I tried a few different things. I was able to reproduce the white screen, but that was caused by FML not being able to display the screen with a list of missing mods. Try it with all mods again and post logs/fml-client-latest.log instead. The log you originally posted doesn't even have a list of all loaded mods.

**Comment by Lunatrius** [comment] 2015-06-26 23:31
Try using Forge 1485. It fixes the white screen issue for the error screens.

**Comment by Lunatrius** [comment] 2015-07-04 18:19
Going to close this. Latest Forge (1485+) should now show the proper error screen.

**Closed by Lunatrius** 2015-07-04 18:19 UTC
Labels: bug
