### ISSUE TITLE
Printer fails to place slabs in the right place

### ISSUE THREAD

**Issue by ghost** [Lunatrius/Schematica#368] opened 2018-07-30 14:58 UTC
Hello!
The building I am trying to print includes many slabs and when the printer is placing them, first it puts them correctly then after some time puts another slab on top of all the other ones, making them full blocks. I tried on both singleplayer, and multiplayer, the issue still occurs.

I demonstrated the issue in this video:
![schematicaproblem](https://user-images.githubusercontent.com/41911938/43405178-ee0d5758-9421-11e8-828e-eddf2699f12f.gif)

I am using;
- Forge 1.12.2 - 14.23.4.2745
- OptiFine 1.12.2 HD U E2
- LunatriusCore 1.12.2 - 1.2.0.42
- Schematica 1.12.2 - 1.8.0.169

Thank you!

**Comment by Lunatrius** [comment] 2018-08-08 13:50
This is an issue that can't be fixed if that is a 1 block wide wall. It tries to place the slabs correctly, but because of the placement logic that means it will right click on the slab bellow, making it fail.

**Comment by Lunatrius** [comment] 2018-09-08 09:30
Actually a duplicate of #358.

**Closed as completed by Lunatrius** 2018-09-08 09:30 UTC
Labels: duplicate, printer
