### ISSUE TITLE
[1.7.10] Client crashes after loading schematic file on FTB

### ISSUE THREAD

**Issue by snoozeville** [Lunatrius/Schematica#151] opened 2016-06-04 09:47 UTC
Every time i load a schematic onto a single-player or multi-player world i crash. I've tried reinstalling it many times, changing ram, ect ect. I also tried installing curse and loading FTB infinity on that but still the same. Crash after crash

http://pastebin.com/PSXYM2vQ

**Comment by RedNesto** [comment] 2016-06-04 10:09
Wow, please avoid documents to download, use https://pastebin.com or https://gist.github.com instead. So this is the "gist version of it: https://gist.github.com/RedNesto/4d37357dc8ed161aed0239cdbdc9adb1

This is also a duplicate of #149 which is NOT closed in this moment. Please check if your problem has been already reported before create a new issue.

**Comment by snoozeville** [comment] 2016-06-04 10:14
Updated the crash report, sorry

**Comment by snoozeville** [comment] 2016-06-04 10:28
http://pastebin.com/PSXYM2vQ

**Comment by RedNesto** [comment] 2016-06-04 10:38
Like I say in the other issue, update your graphic driver and try again.

**Comment by snoozeville** [comment] 2016-06-04 10:43
Already done that, both of my graphic driver are up to date. Intel and NIVIDIA

**Comment by Lunatrius** [comment] 2016-06-04 17:39
It's the same crash.
```
Stack: [0x0000000000b00000,0x0000000000c00000],  sp=0x0000000000bfd0f0,  free space=1012k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [ig75icd64.dll+0x11330]
C  [ig75icd64.dll+0x4d32eb]
C  0x000000000405cb14
 
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 11171  org.lwjgl.opengl.GL11.nglDrawArrays(IIIJ)V (0 bytes) @ 0x000000000405ca8e [0x000000000405ca40+0x4e]
J 24195 C1 org.lwjgl.opengl.GL11.glDrawArrays(III)V (24 bytes) @ 0x0000000005fefe84 [0x0000000005fefa60+0x424]
j  com.github.lunatrius.schematica.client.renderer.RendererSchematicChunk.updateRenderer()V+278
j  com.github.lunatrius.schematica.client.renderer.RendererSchematicGlobal.sortAndUpdate(Lcom/github/lunatrius/schematica/client/world/SchematicWorld;)V+59
```

```
Stack: [0x0000000000940000,0x0000000000a40000],  sp=0x0000000000a3d730,  free space=1013k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [ig75icd64.dll+0x11e8a]
C  [ig75icd64.dll+0x5023ab]
C  0x0000000003c37c54
 
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 10472  org.lwjgl.opengl.GL11.nglDrawArrays(IIIJ)V (0 bytes) @ 0x0000000003c37bce [0x0000000003c37b80+0x4e]
j  org.lwjgl.opengl.GL11.glDrawArrays(III)V+20
j  com.github.lunatrius.schematica.client.renderer.RendererSchematicChunk.updateRenderer()V+306
j  com.github.lunatrius.schematica.client.renderer.RendererSchematicGlobal.sortAndUpdate(Lcom/github/lunatrius/schematica/client/world/SchematicWorld;)V+59
```

The offsets are slightly different, but they both have the same problematic module, namely `ig75icd64.dll`, which is the Intel driver. Have you tried running Minecraft through the NVIDIA GPU instead of the integrated Intel GPU?

**Closed by Lunatrius** 2016-06-04 17:39 UTC
Labels: duplicate
