### ISSUE TITLE
Printer places adjacent blocks, even when placeAdjacent config option set to false

### ISSUE THREAD

**Issue by Epicarseus** [Lunatrius/Schematica#172] opened 2016-08-24 03:36 UTC
The Printer in creative mode attempts to place blocks below the schematic before placing the real blocks. I thought this would be due to the adjacent placement config option, as it seems to be wanting to create a platform, but excess blocks are still placed when the option is disabled. Is there any connection between the two features? In previous versions, I don't recall extra blocks being placed. I also do not see an option to disable extra blocks.

**Comment by Lunatrius** [comment] 2016-08-24 19:24
Duplicate of #170?

**Comment by Epicarseus** [comment] 2016-08-24 21:24
Seems like it. The Schematica version is 1.10.2-1.7.8.151. I am using Forge 12.18.1.2011 on minecraft 1.10.2, and the only other mod is Journey Map. Also, the real block will not be placed until the bottom block has been placed. This is a problem in both Singleplayer and Multiplayer, for both creative and survival for me. The multiplayer server is vanilla. This is what happens:
![2016-08-24_14 14 35](https://cloud.githubusercontent.com/assets/11432983/17948390/8d5ef9a4-6a05-11e6-909c-168f17e231af.png)

**Comment by Lunatrius** [comment] 2016-08-26 13:55
Yes, same issue. I just took a look at the code and it appears that vanilla has fixed the issue. However, the bug shouldn't be happening in SP or a Forge server. I'll keep #170 open until the issue is fixed.

**Closed by Lunatrius** 2016-08-26 13:55 UTC
Labels: bug, duplicate
