### ISSUE TITLE
Crash while using the printer (may be caused by instantaneous block placement config)

### ISSUE THREAD

**Issue by BarbasTheDog** [Lunatrius/Schematica#82] opened 2015-04-11 21:33 UTC
At first I didn't think it was related to Schematica, but then the exact same crash happened a second time while I was using the printer, just like the first time.

http://paste.ee/p/AZ0td

This is all I have :/

**Comment by Lunatrius** [comment] 2015-04-12 00:39
As discussed on IRC, this is most likely not caused directly by Schematica, but the instant placement mode make it highly likely that it will trigger. This could be caused by a core mod tweaking the `updateAllSounds` method to *try* to optimize something.

**Comment by Lunatrius** [comment] 2015-04-19 13:13
Some mod must be either modifying the `updateAllSounds` method or the `playingSounds` map field (second while loop in the 1.7.10 method).
As you've noticed in your SP testing with/without Optifine, it's entirely random when it will happen. It may happen, it may not. It could be just a mod trying to iterate over the sounds in a separate thread at the same time it's trying to play them.

Going to close this for now.

**Closed by Lunatrius** 2015-04-19 13:13 UTC
