### ISSUE TITLE
Server crash on startup 1.9.4

### ISSUE THREAD

**Issue by Claycorp** [Lunatrius/Schematica#162] opened 2016-07-07 23:53 UTC
http://pastebin.com/7X1ZXw91

**Comment by Lunatrius** [comment] 2016-07-08 08:01
Not entirely sure why it happens, but I doubt that I'll be fixing this in 1.9.4. I can barely keep up with the latest version. Will be fixed in 1.10.2 for sure.

**Comment by RedNesto** [comment] 2016-07-08 09:50
I'm not sure but I think I have found a solution (but probably not the better). Whatever it works, for me at least:

```
private MinecraftServer minecraftServer = FMLServerHandler.instance().getServer();

    @Override
    public File getDataDirectory() {
        if(this.minecraftServer != null) {
            Reference.logger.info("server instance is not null !");
        }
        final File file = this.minecraftServer.getFile(".");
        // I haven't touched the rest of the method
```

The version i have compiled with these changes: https://mega.nz/#!OxNQXDST!N7Ge4aLkX2ijykiPK2LyhKFJKGYFZ6t7-xMTVlXNHiE

**Comment by RedNesto** [comment] 2016-07-08 10:12
I think the problem is the use of WeakReference during the starting event (Instance not ready ?)

My solution:
```
    private final WeakReference<MinecraftServer> serverWeakReference = new WeakReference<MinecraftServer>(FMLServerHandler.instance().getServer());

    @Override
    public void serverStarting(final FMLServerStartingEvent event) {
        super.serverStarting(event);
        event.registerServerCommand(new CommandSchematicaDownload());
    }

    @Override
    public File getDataDirectory() {
        final MinecraftServer server = serverWeakReference.get();
        final File file = server != null ? server.getFile(".") : new File(".");
        try {
            return file.getCanonicalFile();
        } catch (final IOException e) {
            Reference.logger.info("Could not canonize path!", e);
        }
        return file;
    }
```

The compiled jar with the previous code: https://mega.nz/#!SsszwC6a!3xr6WIDZLiUuZkWu6RTLh0t4FUsqEYuG7J9s_lLur2o

**Closed** 2016-07-08 13:59 UTC
Labels: bug
