### ISSUE TITLE
Printer not working for 1.7.10 schematica

### ISSUE THREAD

**Issue by KingSqurrill** [Lunatrius/Schematica#175] opened 2016-08-29 02:28 UTC
Hi i have had schematica for a while and its a really good tool, but what sucks is that the printer tool doesn't work for me. I play on forge and my brother uses technic, and on technic with the exact same versions it works fine for him but on forge it doesn't work for me. Any and all help with this issue would be extremely appreciated :) thank you in advance

**Comment by Lunatrius** [comment] 2016-08-29 14:25
Are you on a server? Also upload the `fml-client-latest.log` log file to gist and post the link here.

**Comment by KingSqurrill** [comment] 2016-08-31 03:47
yea, I'm on a server

**Comment by KingSqurrill** [comment] 2016-08-31 03:48
could u be more specific with those directions? I'm sorry but i didn't understand half those words

**Comment by Lunatrius** [comment] 2016-08-31 14:08
Chances are that the server disabled the use of Schematica. The log file `fml-client-latest.log` located inside `.minecraft/logs` most likely contains a line that says `Printer is disabled on this server.`

**Comment by KingSqurrill** [comment] 2016-08-31 17:50
im 100% sure it doesn't block schematica, i have seen my brother (as i said up there) use printer on the same exact server, and staff/freinds on the server use it also

**Comment by Lunatrius** [comment] 2016-08-31 22:01
I can't really tell you what's wrong unless I can see what is going on - by looking at the log file.

**Comment by KingSqurrill** [comment] 2016-09-01 06:28
[fml-client-latest.log.zip](https://github.com/Lunatrius/Schematica/files/448946/fml-client-latest.log.zip)   
maybe this can help?

**Comment by KingSqurrill** [comment] 2016-09-02 05:35
uhm... can i do something else or have u just not had time to respond? (not trying to be buggy/rude)

**Comment by Lunatrius** [comment] 2016-09-03 10:45
I'm not entirely sure what is going on. There is nothing in the log file that would indicate that the printer is disabled/broken.

**Comment by KingSqurrill** [comment] 2016-09-05 06:23
Is there something else I could send? When I activate printer the pinwheel just starts spinning as my game freezes, and I crash

**Comment by Lunatrius** [comment] 2016-09-05 18:33
> the pinwheel just starts spinning as my game freezes, and I crash

That's an important piece information that you've left out previously. Does it crash on it's own or do you have to forcefully close it? Is there any file in the .minecraft folder that starts/ends with `hid` or `pid` or `hpid` (can't remember the exact string right now)?

**Comment by KingSqurrill** [comment] 2016-09-05 18:44
i wasn't able to find this folder, I'm on mac if that helps, and it crashes on its own

**Comment by KingSqurrill** [comment] 2016-09-05 18:46
file* not folder

**Comment by Lunatrius** [comment] 2016-09-05 18:56
Can you delete the `crash-logs` and `logs` folders and try to use the printer and let it crash? It should generate a crash report inside the `crash-logs` folder.

**Comment by KingSqurrill** [comment] 2016-09-05 19:05
[crash-2016-09-05_15.04.58-client.txt.zip](https://github.com/Lunatrius/Schematica/files/455529/crash-2016-09-05_15.04.58-client.txt.zip)
this is all thats in crash reports now

**Comment by Lunatrius** [comment] 2016-09-05 19:45
```
java.lang.NoSuchMethodError: net.minecraft.block.Block.getPickBlock(Lnet/minecraft/util/MovingObjectPosition;Lnet/minecraft/world/World;IIILnet/minecraft/entity/player/EntityPlayer;)Lnet/minecraft/item/ItemStack;
	at com.github.lunatrius.schematica.client.util.BlockToItemStack.getItemStack(BlockToItemStack.java:14)
	at com.github.lunatrius.schematica.client.printer.SchematicPrinter.placeBlock(SchematicPrinter.java:169)
	at com.github.lunatrius.schematica.client.printer.SchematicPrinter.print(SchematicPrinter.java:114)
	at com.github.lunatrius.schematica.handler.client.TickHandler.onClientTick(TickHandler.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_66_TickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2053)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Duplicate of #95. Update Forge to **10.13.2.1234** or later and you should be fine.

**Closed by Lunatrius** 2016-09-05 19:45 UTC
Labels: duplicate

**Comment by KingSqurrill** [comment] 2016-09-06 02:24
i love you :D
