### ISSUE TITLE
Orange dispensers

### ISSUE THREAD

**Issue by secretassassin818** [Lunatrius/Schematica#160] opened 2016-07-04 18:02 UTC
Idk why but when I turn on printer for cannons, some dispensers are orange and I dont know why. They are facing the correct way and  everything

**Comment by RedNesto** [comment] 2016-07-04 18:49
That sounds weird, which version do you use ?

**Comment by Lunatrius** [comment] 2016-07-04 20:58
Can you make a screenshot while having F3 open (while pointing at the dispenser)?

**Comment by RedNesto** [comment] 2016-07-05 07:08
Here it is: 
![2016-07-05_15 04 06](https://cloud.githubusercontent.com/assets/13600250/16576431/c8728b48-42c1-11e6-9938-3edc7f68c9e6.png)

I forgot to mention something: when clicking on orange dispensers, they becomes valid

**Comment by secretassassin818** [comment] 2016-07-05 19:48
I use 1.8-1.1.2.30 which is just mc 1.8

**Comment by Lunatrius** [comment] 2016-07-05 20:15
Not a bug, the default state seems to have changed - you can see the triggered properties on the right side of the screen aren't the same. Saving the structure again should make it valid for all future versions until something changes again.

**Comment by secretassassin818** [comment] 2016-07-05 21:39
ok thank you

**Comment by Lunatrius** [comment] 2016-07-10 13:00
Closing this as a non issue, since this is a vanilla change. The schematics have to be re-saved to work properly again on 1.9+.

**Closed by Lunatrius** 2016-07-10 13:00 UTC
Labels: not-a-bug
