### ISSUE TITLE
all my files load on a wierd way

### ISSUE THREAD

**Issue by jeroen11122005** [Lunatrius/Schematica#378] opened 2018-08-23 13:11 UTC
https://gyazo.com/d7d4a47fdb89c146415dc9d80c12989f wierd things like this happend to all my files when i try to load them i tryd reinstalling the mod but nothing works

**Comment by Pokechu22** [comment] 2018-08-23 16:03
Duplicate of #258.  This is caused by optifine.  You may be able to bypass it by toggling VBOs, though.

**Closed as completed** 2018-08-23 23:02 UTC
Labels: duplicate, optifine, incompatibility
