### ISSUE TITLE
[Suggestion] AFK Mode (Or AutoWalk)

### ISSUE THREAD

**Issue by Novitex** [Lunatrius/Schematica#247] opened 2017-08-04 21:01 UTC
I enjoy using this mod a lot. However, it would be great (and convenient) for me if you added an AFK Mode. What I mean by this is by making it automatically walk to a place that needs building instead of you manually walking to a place that needs building.

For example, when I'm building, I would usually manually walk around the schematic while the printer is building. But, with afk mode on, I wouldn't have to press any buttons. When part of the schematic is already built, it would automatically walk me to another part of the schematic and build that part. and it would repeatedly keep doing that until the build is done. 

I hope this is not too hard to implement. If you do implement this into Schematica though, it would definitely be a great addition. 👍

**Comment by Lunatrius** [comment] 2017-08-05 00:56
This is a duplicate of #48 #91 #102.

I doubt that I'll ever implement the feature directly into the mod. It's supposed to be a guidance/helper mod that assists you with your builds. Turning it into a bot is not something that I'd want to do, nor is it easy to do.

**Comment by Novitex** [comment] 2017-08-05 21:57
close #247

**Closed** 2017-08-08 06:22 UTC
Labels: duplicate, enhancement, printer
