### ISSUE TITLE
Crash on all schematics

### ISSUE THREAD

**Issue by Arkhorse** [Lunatrius/Schematica#329] opened 2018-04-23 05:48 UTC
So, Im playing on a private server, and I am making a service shop for the server. I go into a creative testing/ building world, and make a simple shop. And it crashes when loading. This also happens when loading an other schem as well. Here are two crash logs:

Single Player:
[crash-2018-04-23_02.24.45-client.txt](https://github.com/Lunatrius/Schematica/files/1936822/crash-2018-04-23_02.24.45-client.txt)
[crash-2018-04-23_02.40.37-client.txt](https://github.com/Lunatrius/Schematica/files/1936823/crash-2018-04-23_02.40.37-client.txt)

On the server:
[crash-2018-04-23_02.34.57-client.txt](https://github.com/Lunatrius/Schematica/files/1936824/crash-2018-04-23_02.34.57-client.txt)

Any idea on what could be causing this?

**Comment by Pokechu22** [comment] 2018-04-23 05:51
Duplicate of #321; this is caused by optifine's Render Regions settings.  Either remove optifine or disable that setting.

**Comment by Arkhorse** [comment] 2018-04-23 05:53
Would it be possible to pin that issue? So that no one needs to open another issue tracker?

**Comment by Pokechu22** [comment] 2018-04-23 05:55
I don't think GitHub lets you do that, but it might be possible to note it on the forum thread/the download page.

**Comment by Arkhorse** [comment] 2018-04-23 06:04
Yeah, Maybe a section with Known stuff like this.

**Comment by Lunatrius** [comment] 2018-04-24 07:16
Even if it was possible to pin issues, rarely anyone would read them. It's easier to close issues as duplicates.

**Closed as completed by Lunatrius** 2018-04-24 07:16 UTC
Labels: optifine, incompatibility, mc-1.12
