### ISSUE TITLE
[1.12] Placement Speed 

### ISSUE THREAD

**Issue by DerChronix** [Lunatrius/Schematica#239] opened 2017-07-19 16:03 UTC
Hi, Since im Playing on a Multiplayer Towny Server There is an Anticheat that Let me just use Schematica if the Placement Speed is set almost to The Lowest, and since the Config isnt Working cause its Grayed, I tried to Find it in The files, But i wasnt Really successfull, So i wanted to ask If someone Could say me Where i Can Change the Placement Speed in the Schematica Files.

**Comment by Lunatrius** [comment] 2017-07-19 16:21
You're not using an official release and I can't treat this issue as a valid bug report.

It looks like a Forge issue, I'll make sure to look into this while updating to 1.12.

**Comment by DerChronix** [comment] 2017-07-19 16:26
Is there Any Estimated Official release Date? im Waiting Since 1.12 Came out and still nothing, thats really sad, its more then a month already

**Comment by Lunatrius** [comment] 2017-07-19 17:00
I wanted to get a majority of the work that I already started last week done today, but something unexpected came up.

I'll try to push some of the other stuff on the side to get the updates out as soon as possible, preferably until the end of this week.

**Comment by Lunatrius** [comment] 2017-07-25 12:20
Test it again using the official version.

**Comment by Lunatrius** [comment] 2017-07-31 21:35
I assume that the issue is fixed with the official release.

If it's not, please re-open the issue.

**Closed by Lunatrius** 2017-07-31 21:35 UTC
Labels: bug, invalid, mc-1.12
