### ISSUE TITLE
Glitched blockes

### ISSUE THREAD

**Issue by xKydro** [Lunatrius/Schematica#344] opened 2018-06-10 16:41 UTC
![image](https://user-images.githubusercontent.com/40146877/41203884-95ba369c-6c9a-11e8-87f7-aaa6b258d6ef.png)
 I have re-installed schematica and Lunatrius Core at least 3 times now, the display nor the print functions are working, any help?

**Comment by Pokechu22** [comment] 2018-06-10 16:45
Duplicate of #258; caused by optifine.  Either remove optifine, or disable VBOs (which sometimes works).

**Closed as completed** 2018-06-13 07:34 UTC
Labels: duplicate
