### ISSUE TITLE
Game crashes when loading any schematic

### ISSUE THREAD

**Issue by SantaDabbing** [Lunatrius/Schematica#374] opened 2018-08-17 21:31 UTC
My schematic mod was working completely fine last night. Now whenever I try to load any schematic, it just crashes. 

Here is the crash report
[crash report.txt](https://github.com/Lunatrius/Schematica/files/2298790/crash.report.txt)

**Comment by Pokechu22** [comment] 2018-08-17 21:45
Duplicate of #321, caused by optifine's "render regions" setting.

**Comment by SantaDabbing** [comment] 2018-08-17 21:45
so do i have to turn off optifine for it to work?

**Comment by Pokechu22** [comment] 2018-08-17 21:47
At minimum you'll need to disable its render regions setting; however, optifine has caused other compatibility issues in the past too so removing it entirely may make sense if you keep running into other problems.

**Comment by SantaDabbing** [comment] 2018-08-17 21:48
ok thank you so much, ill give that a shot right now and post the result here

**Comment by SantaDabbing** [comment] 2018-08-17 21:51
i removed optifine completely from the mods folder and it works perfectly now. thank you so much for the help

**Comment by Lunatrius** [comment] 2018-08-19 15:34
You can also try turning VBOs OFF in the settings.

**Closed as completed by Lunatrius** 2018-08-19 15:34 UTC
Labels: duplicate, optifine, incompatibility
