### ISSUE TITLE
Game Crash when schematic is imported.

### ISSUE THREAD

**Issue by DozenalGD** [Lunatrius/Schematica#363] opened 2018-07-21 23:05 UTC
Game crashes after about 10 seconds of loading in a schematic. Tried reloading chunks, redownloading the latest versions of both Schematica and Lunatrius Core, no improvement. [fml-client-latest.log](https://github.com/Lunatrius/Schematica/files/2216580/fml-client-latest.log)

**Comment by DozenalGD** [comment] 2018-07-21 23:31
Disregard, had something to do with render distance. I'd love to hear what went wrong so I can fix in the future.

**Comment by DozenalGD** [comment] 2018-07-21 23:32
Disregard, it is now fixed, had something to do with render distance, I'd still appreciate if you took a look at what went wrong and tell me so I can fix it if it happens again in he future.

**Comment by DozenalGD** [comment] 2018-07-22 02:00
Here is a recent crash report.
[crash-2018-07-21_21.58.57-client.txt](https://github.com/Lunatrius/Schematica/files/2216663/crash-2018-07-21_21.58.57-client.txt)

**Comment by Pokechu22** [comment] 2018-07-22 02:08
This is a duplicate of #321, caused by Optifine's Render Regions setting.

**Comment by DozenalGD** [comment] 2018-07-22 02:33
Thanks.

**Closed as completed** 2018-07-22 02:34 UTC
Labels: duplicate, optifine
