### ISSUE TITLE
Blocks not showing?

### ISSUE THREAD

**Issue by MERCHIE** [Lunatrius/Schematica#152] opened 2016-06-14 07:37 UTC
When I load a schematic it only shows the outline.
http://imgur.com/2EkNtBL

**Comment by RedNesto** [comment] 2016-06-14 07:47
Have you tried without ressource pack ?

**Comment by MERCHIE** [comment] 2016-06-14 07:48
Yes and it stills happens

**Comment by RedNesto** [comment] 2016-06-14 07:51
Which version of  Minecraft / Schematica / LunatriusCore  are you using ?

**Comment by MERCHIE** [comment] 2016-06-14 07:53
Both are 1.9.4 and so is optifine and forge

**Comment by RedNesto** [comment] 2016-06-14 08:02
What blocks are on the schematic ?

**Comment by MERCHIE** [comment] 2016-06-14 08:11
stairs, snow, clay, stuff like that

**Comment by RedNesto** [comment] 2016-06-14 08:13
I've edited the message -> refresh this page. ;)

**Comment by MERCHIE** [comment] 2016-06-14 08:16
how do i change that? sorry im not great with this stuff lol

**Comment by RedNesto** [comment] 2016-06-14 08:21
If you don't like make changes directly in the file:

1. go on _Mod Options_ or _Mods_ menu
2. select _Schematica_ then click _Config_ wich is below
3. open the _Rendering_ tab
4. set _Alpha Enabled_ to _false_

**Comment by MERCHIE** [comment] 2016-06-14 08:25
hmm it already is

**Comment by RedNesto** [comment] 2016-06-14 08:28
Is the _Reset to Default_ button clickable on the config panel ?

**Comment by MERCHIE** [comment] 2016-06-14 08:29
no

**Comment by RedNesto** [comment] 2016-06-14 08:30
Have you reload your world between manipulations ?

**Comment by MERCHIE** [comment] 2016-06-14 08:32
just tried and nothings changed

**Comment by RedNesto** [comment] 2016-06-14 08:34
Have you click _Done_ after changes to config ?

**Comment by MERCHIE** [comment] 2016-06-14 08:35
yeah

**Comment by RedNesto** [comment] 2016-06-14 08:36
And that doesn't work ?

**Comment by MERCHIE** [comment] 2016-06-14 08:37
no, maybe ill download them again and try that

**Comment by Lunatrius** [comment] 2016-06-20 07:17
Closing this - if you're still having the issue, feel free to re-open this ticket.

**Closed by Lunatrius** 2016-06-20 07:17 UTC

**Comment by TryHardHusky** [comment] 2017-02-08 01:56
Came across this issue, Turns out it was the shader I was using. Turn that off and the blocks will show.

**Comment by 341025245** [comment] 2018-06-05 00:23
I have the exact same issue. 
I re-downloaded schematica and this issue still persists. 
I even tried with an alternate older version of schematica, and it still only shows the outline. 
I'm using the 1.8.9 versions.

**Comment by Lunatrius** [comment] 2018-06-13 07:28
I no longer support old Minecraft versions, sorry.

**Comment by Flavius2705** [comment] 2018-06-28 17:24
I have the same problem in 1.12.2 tried everything from above , even reinstaling minecraft , still doesent work ... help ?

**Comment by Lunatrius** [comment] 2018-06-28 21:05
Have you tried any of the suggested fixes? Shaders, Optifine etc.

**Comment by Flavius2705** [comment] 2018-06-28 21:48
Yes

**Comment by Flavius2705** [comment] 2018-06-28 21:56
I am using SK launcher , maybe the launcher its the cause ?

**Comment by Lunatrius** [comment] 2018-06-29 06:57
It worth trying it with another launcher. Also try to install just LunatriusCore and Schematica.

**Comment by EGURT1** [comment] 2018-07-08 14:48
@MERCHIE What version of Optifine are you using ?

**Comment by EGURT1** [comment] 2018-07-12 13:38
@MERCHIE try using this version of optifne 1.12.2 [HD U C9](https://optifine.net/adloadx?f=OptiFine_1.12.2_HD_U_C9.jar)

**Comment by iammeat** [comment] 2019-02-01 10:35
I'm encountering the exact same issue.  Minecraft 1.12.2 and only Core and Schematica installed.  It is only loading a little over a quarter of my schematic.

Here's a link to the schematic: [IslandBase](https://filebin.net/2ptyhmramvlc2fx2/IslandBase.schematic?t=2aoz4chp)

When I load this [vertical cactus farm](https://filebin.net/2ptyhmramvlc2fx2/CactusFarm.schematic?t=2aoz4chp), it loads without issue, however.

**Comment by Icebluewolf** [comment] 2019-02-02 12:55
Make sure you are within a 3 block radius of the blocks. So if it is tall you will have to build/fly up to the top. Your fist also might start randomly punching but that is ok.

**Comment by iammeat** [comment] 2019-02-02 13:49
@Icebluewolf I've tried to print even though the blocks aren't showing, but it won't build any of the invisible blocks.  Any other things I should try?  Did you take a look at the two schematics I attached?

**Comment by Icebluewolf** [comment] 2019-02-02 13:59
No I can look at it later
But i am new to this mod too so if it just builds a portion of the build I
think what I said erlyer was the issue.

**Comment by Xelbayria** [comment] 2020-05-27 01:39
Hello, 

I've set the alpha to "False" and set Alpha to "0" as well. nothing works. 
I also have Optifine and Schematica and the core mod. 

here's a picture: 
https://imgur.com/DL4ibSL

do anyone know what's causing it.

**Comment by Aquellare** [comment] 2020-11-06 01:36
I finally find where the problem is, its in optifine. The mod was working without any problems but when i started to configurate the optifine graphics settings suddenly the blocks stoped showing i dont know exactly what graphic configuration is making the blocks dont show but when i find it i will edit this comment (srry my english sucks) **_SOLUTION: The problem is in Graphics, Performance, Render Regions, Change Render Regions to OFF_**

**Comment by PainXDYT** [comment] 2023-07-19 13:16
@Aquellare  I turned it off but it still isnt fixed, im on optifine too but it doesnt show any blocks, do you have any other solutions you havent shown, im a bit 2 years late for this but anything new?????? if not, i think i wasted morethan 3 years of building smth for schematica

**Comment by dko1905** [comment] 2024-09-09 13:11
I recently experienced the same issue on Enigmatica 2: Expert with Optifine.
**SOLUTION: *Graphics* -> Change *Use VBOs* to *OFF***
It does impact performance though
